### ISSUE TITLE
coefficient_variation_flags.py error when dropping missing data.

### ISSUE THREAD

**Issue by moskalenko** [secimTools/SECIMTools#3]
Command Line

coefficient_variation_flags.py --input /bio/galaxy/run/prod/galaxy/database/files/000/562/dataset_562275.dat --design /bio/galaxy/run/prod/galaxy/database/files/000/562/dataset_562261.dat --ID row_ID --figure /bio/galaxy/run/prod/galaxy/database/jobs_directory/000/291/291186/outputs/galaxy_dataset_bf80656d-6c96-4426-90d6-fdd47582c0d9.dat --flag /bio/galaxy/run/prod/galaxy/database/jobs_directory/000/291/291186/outputs/galaxy_dataset_9bdafd7e-0703-4dd8-8d0f-e1e777f6ceb3.dat --CVcutoff 0.1

stderr

Matplotlib created a temporary config/cache directory at /scratch/local/4432460/matplotlib-fsw38tat because the default path (/root/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib is building the font cache; this may take a moment.
Traceback (most recent call last):
  File "/bio/galaxy/run/prod/galaxy/database/dependencies/_conda/envs/__secimtools@21.4.15/bin/coefficient_variation_flags.py", line 285, in <module>
    main(args)
  File "/bio/galaxy/run/prod/galaxy/database/dependencies/_conda/envs/__secimtools@21.4.15/bin/coefficient_variation_flags.py", line 240, in main
    dat.dropMissing()
  File "/bio/galaxy/run/prod/galaxy/database/dependencies/_conda/envs/__secimtools@21.4.15/lib/python3.9/site-packages/secimtools/dataManager/interface.py", line 373, in dropMissing
    if np.isnan(self.wide.values).any():
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

stdout

2021-07-07 09:44:43,101 - INFO - Importing data with following parameters: 
	Wide: /bio/galaxy/run/prod/galaxy/database/files/000/562/dataset_562275.dat
	Design: /bio/galaxy/run/prod/galaxy/database/files/000/562/dataset_562261.dat
	Unique ID: row_ID
	Group: False
2021-07-07 09:44:43,103 - INFO - Using Tableau_20 color scheme from tableau palette
2021-07-07 09:44:43,103 - INFO - Groups used to color by: 
2021-07-07 09:44:43,465 - INFO - Inferring 'sampleID' from data. This will accept different capitalizations of the word

**Comment by moskalenko** [comment]
This issue was caused by invalid data. One of the metabolites had data as "123,456,78" numbers (with commas and quotes), which wasn't converted to numeric values by pandas during the import and caused the missing value unsupported input type error.
